import type { Metadata } from "next";
import { Inter, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
// 1. Import your Provider and Navbar
import { CartProvider } from "@/context/CartContext";
import FloatingNav from "@/components/FloatingNav";

const inter = Inter({ subsets: ["latin"] });
const cormorant = Cormorant_Garamond({
  weight: ['300', '400', '500'],
  subsets: ["latin"],
  variable: '--font-cormorant'
});

export const metadata: Metadata = {
  title: "My Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${cormorant.variable}`}>
        {/* 2. Wrap EVERYTHING inside the body with CartProvider */}
        <CartProvider>

          {/* Now FloatingNav can use useCart because it's inside the Provider */}
          <FloatingNav />

          {/* All your pages (children) can also use the cart */}
          {children}

        </CartProvider>
      </body>
    </html>
  );
}