import type { Metadata, Viewport } from "next";
import { Inter, Cormorant_Garamond, Playfair_Display, Allura } from "next/font/google";
import "./globals.css";
// 1. Import your Provider and Navbar
import { CartProvider } from "@/context/CartContext";
import FloatingNav from "@/components/FloatingNav";
import FloatingLogo from "@/components/FloatingLogo";

const inter = Inter({ subsets: ["latin"] });
const cormorant = Cormorant_Garamond({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ["latin"],
  style: ['normal', 'italic'],
  variable: '--font-cormorant'
});
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: '--font-playfair'
});
const allura = Allura({
  weight: "400",
  subsets: ["latin"],
  variable: '--font-allura'
});

export const metadata: Metadata = {
  title: "My Store",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1.0,
  maximumScale: 1.0,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${cormorant.variable} ${playfair.variable} ${allura.variable}`}>
        {/* 2. Wrap EVERYTHING inside the body with CartProvider */}
        <CartProvider>

          {/* Now FloatingNav can use useCart because it's inside the Provider */}
          <FloatingNav />
          <FloatingLogo />

          {/* All your pages (children) can also use the cart */}
          {children}

        </CartProvider>
      </body>
    </html>
  );
}